version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies (no frozen lockfile)
          command: yarn install --no-frozen-lockfile
      - run:
          name: Set NOTION_TOKEN for build
          command: |
            if [ -z "$NOTION_TOKEN" ]; then
              echo "ERROR: NOTION_TOKEN environment variable is not set. Please add it to your CircleCI project or context."
              exit 1
            fi
      - run:
          command: yarn run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
workflows:
  build:
    jobs:
      - build-node